FROM jenkins/jenkins:lts-jdk17

USER root

# -------------------------------
# Install Docker CLI
# -------------------------------
RUN apt-get update && apt-get install -y lsb-release \
  && curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
     https://download.docker.com/linux/debian/gpg \
  && echo "deb [arch=$(dpkg --print-architecture) \
     signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
     https://download.docker.com/linux/debian \
     $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list \
  && apt-get update && apt-get install -y docker-ce-cli \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------
# Install Terraform
# -------------------------------
ENV TERRAFORM_VERSION=1.6.6

RUN apt-get update && apt-get install -y wget unzip gnupg software-properties-common \
  && wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
  && unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
  && mv terraform /usr/local/bin/ \
  && rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
  && terraform version \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------
# Install AWS CLI v2
# -------------------------------
RUN apt-get update && apt-get install -y curl unzip \
  && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
  && unzip awscliv2.zip \
  && ./aws/install \
  && rm -rf awscliv2.zip aws \
  && aws --version \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------
# Switch back to Jenkins user
# -------------------------------
USER jenkins
